"""Traces whose sharing structure is written down in the file.

Four columns, plus `# LEN` declarations in the header:

    # SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.
    # LEN SYS:assistant_v3=180
    # LEN FEW:math_5shot=420
    # LEN USR:q0000=37
    request_id,arrival_s,segments,output_tokens
    r0000,0.000000,SYS:assistant_v3|FEW:math_5shot|USR:q0000,64

Lengths live in the header rather than beside each use because a segment name is a
promise that the tokens are identical, and identical tokens have one length. The
loader enforces it: the same label declared twice with different lengths is an
error, not a warning.

Why the structure is in the file rather than in the generator
------------------------------------------------------------
Every published prefix-cache number depends on how much the traffic shares, and
that quantity is almost always an assumption nobody wrote down. Here it is a column.
A reader can compute the reuse ceiling from the `segments` column with a pencil,
which is what makes the tool's answer checkable rather than merely plausible.
"""
import csv

from .segments import Registry, SegmentError, expand, parse_spec


class TraceError(ValueError):
    pass


class Request:
    __slots__ = ("id", "arrival_s", "segments", "output_tokens", "_tokens")

    def __init__(self, id, arrival_s, segments, output_tokens):
        if arrival_s < 0:
            raise TraceError(f"{id}: negative arrival {arrival_s}")
        if output_tokens < 1:
            raise TraceError(f"{id}: output_tokens must be at least 1")
        if not segments:
            raise TraceError(f"{id}: no segments")
        self.id = id
        self.arrival_s = float(arrival_s)
        self.segments = list(segments)
        self.output_tokens = int(output_tokens)
        self._tokens = None

    @property
    def spec(self):
        return "|".join(s.label for s in self.segments)

    @property
    def prompt_tokens(self):
        return sum(s.length for s in self.segments)

    def token_ids(self):
        """Expanded lazily and cached: a trace of 400 requests with 4 kB prompts is
        1.6 M ids, and most analyses touch each request once."""
        if self._tokens is None:
            self._tokens = expand(self.segments)
        return self._tokens

    def __repr__(self):
        return (f"Request({self.id!r}, t={self.arrival_s:.3f}, "
                f"{self.prompt_tokens} prompt tokens, {self.spec})")


class Trace:
    def __init__(self, requests, registry, source="<memory>", declared=""):
        self.requests = sorted(requests, key=lambda r: (r.arrival_s, str(r.id)))
        self.registry = registry
        self.source = source
        self.declared = declared
        if not self.requests:
            raise TraceError(f"{source}: a trace with no requests")

    def __len__(self):
        return len(self.requests)

    def __iter__(self):
        return iter(self.requests)

    @property
    def span_s(self):
        return self.requests[-1].arrival_s - self.requests[0].arrival_s

    @property
    def prompt_tokens(self):
        return sum(r.prompt_tokens for r in self.requests)

    def segment_usage(self):
        """How many requests name each segment. The sharing structure, tabulated.

        A segment used once can never be reused; a segment used 200 times is where
        all the value is. Printing this next to a hit rate is what stops somebody
        attributing the traffic's repetitiveness to the cache.
        """
        counts = {}
        for r in self.requests:
            for s in r.segments:
                counts[s.label] = counts.get(s.label, 0) + 1
        return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))

    def summary(self):
        usage = self.segment_usage()
        reused = {k: v for k, v in usage.items() if v > 1}
        shared_tokens = sum(self.registry.get(k).length * (v - 1)
                            for k, v in reused.items())
        return {
            "requests": len(self.requests),
            "span_s": round(self.span_s, 4),
            "prompt_tokens": self.prompt_tokens,
            "distinct_segments": len(usage),
            "reused_segments": len(reused),
            # Tokens that appear in more than one request, counted once per repeat.
            # An upper bound on reuse that ignores block alignment and position --
            # `oracle.py` computes the real ceiling.
            "repeated_tokens_naive": shared_tokens,
            "declared": self.declared,
        }

    def __repr__(self):
        return f"Trace({len(self.requests)} requests, {self.source!r})"


def load(path):
    declared, lengths, rows = [], {}, []
    with open(path, newline="", encoding="utf-8") as fh:
        body = []
        for line in fh:
            if line.startswith("#"):
                text = line[1:].strip()
                if text.startswith("LEN "):
                    label, _, n = text[4:].partition("=")
                    if not n:
                        raise TraceError(f"{path}: malformed LEN line {text!r}")
                    lengths[label.strip()] = int(n)
                else:
                    declared.append(text)
            else:
                body.append(line)
        reader = csv.DictReader(body)
        if reader.fieldnames is None:
            raise TraceError(f"{path}: no header row")
        need = {"arrival_s", "segments", "output_tokens"}
        missing = need - set(reader.fieldnames)
        if missing:
            raise TraceError(f"{path}: missing column(s) {', '.join(sorted(missing))}")
        registry = Registry()
        for i, row in enumerate(reader):
            rid = row.get("request_id") or f"r{i}"
            try:
                segs = parse_spec(row["segments"], registry, lengths)
                rows.append(Request(rid, float(row["arrival_s"]), segs,
                                    int(row["output_tokens"])))
            except (SegmentError, TypeError, ValueError) as exc:
                raise TraceError(f"{path}: row {i + 1}: {exc}") from None
    unused = sorted(set(lengths) - set(registry.labels()))
    if unused:
        raise TraceError(
            f"{path}: declared lengths for {', '.join(unused)} but no request uses "
            "them. An unused declaration is either a typo in a segments column or a "
            "leftover, and both change what the sharing structure looks like.")
    return Trace(rows, registry, source=str(path), declared=" ".join(declared))


def write(path, trace, declaration=""):
    with open(path, "w", newline="", encoding="utf-8") as fh:
        if declaration:
            for line in declaration.splitlines():
                fh.write(f"# {line}\n")
        for label in trace.registry.labels():
            fh.write(f"# LEN {label}={trace.registry.get(label).length}\n")
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["request_id", "arrival_s", "segments", "output_tokens"])
        for r in trace:
            w.writerow([r.id, f"{r.arrival_s:.6f}", r.spec, r.output_tokens])


__all__ = ["Request", "Trace", "TraceError", "load", "write"]
