"""Generate the example traces. Deterministic, no dependencies, no clock.

    python tests/traces/make_traces.py

Re-running must reproduce every file byte for byte; CI checks it with
`git diff --exit-code`. A generated fixture that has drifted from its generator is a
fixture nobody can check.

Seven shapes, chosen because they put the limit in different places. A set of traces
where the cache ranks the same on all of them would prove nothing:

    system_prompt   one shared preamble, unique questions -- the common deployment
    multiturn       a growing shared prefix inside each conversation
    agent           a tool loop appending to a long context, very short answers
    fewshot         two levels of sharing: global preamble, per-task examples
    no_sharing      **the control.** Nothing is shared. A cache must report zero
                    here, and if it does not, everything else in the suite is noise
    shared_last     the same content as system_prompt with the shared part moved
                    *after* the unique part, which destroys all of it. This is the
                    mistake PK001 exists to catch, and it is here so the rule can be
                    demonstrated rather than asserted
    tiny            twelve requests, small enough to check the whole thing by hand

Segment lengths are deliberately not multiples of 16. A 180-token system prompt
loses 4 tokens to a 16-token block and 52 to a 64-token block, and that loss is one
of the things this library is for; rounding the fixtures to 192 would hide it.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from prefixkv.segments import Registry  # noqa: E402
from prefixkv.trace import Request, Trace, write  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))


class LCG:
    """Numerical Recipes constants. Enough for fixtures, not for anything else."""

    def __init__(self, seed):
        self.state = seed & 0xFFFFFFFF

    def next(self):
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state

    def randint(self, lo, hi):
        return lo + self.next() % (hi - lo + 1)

    def uniform(self):
        return self.next() / 0x100000000


def build(name, declaration, rows, reg=None):
    """`rows` is a list of (request_id, arrival_s, [(kind, name, length)], output)."""
    reg = reg or Registry()
    reqs = []
    for rid, t, spec, out in rows:
        segs = [reg.declare(k, n, ln) for k, n, ln in spec]
        reqs.append(Request(rid, t, segs, out))
    trace = Trace(reqs, reg, source=name)
    write(os.path.join(HERE, name), trace, declaration=declaration)
    s = trace.summary()
    print(f"{name:<34} n={s['requests']:<4} prompt={s['prompt_tokens']:<8} "
          f"segments={s['distinct_segments']:<5} reused={s['reused_segments']}")
    return trace


def system_prompt():
    rng = LCG(20260817)
    rows = []
    t = 0.0
    for i in range(160):
        t += rng.uniform() * 2.0
        rows.append((f"r{i:04d}", t,
                     [("SYS", "assistant_v3", 180),
                      ("USR", f"q{i:04d}", rng.randint(24, 90))],
                     rng.randint(40, 240)))
    build("EXAMPLE_system_prompt.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "One 180-token system prompt shared by every request, then a unique\n"
          "question of 24-90 tokens. The shape almost every deployment has, and the\n"
          "one where a hit rate looks most impressive for reasons that have nothing\n"
          "to do with the cache: the shared part is a fixed fraction of the prompt,\n"
          "so the hit rate is set by that fraction and not by the policy.", rows)


def multiturn():
    rng = LCG(20260818)
    rows = []
    t = 0.0
    rid = 0
    for conv in range(24):
        # Each turn's prompt is the system prompt plus every earlier turn of this
        # conversation plus the new question. The shared prefix grows by one turn
        # each time, which is where the logit rule costs a whole block per turn.
        history = []
        for turn in range(rng.randint(3, 8)):
            t += rng.uniform() * 3.0
            question = ("USR", f"c{conv:02d}t{turn:02d}", rng.randint(20, 70))
            spec = [("SYS", "chat_v1", 96)] + list(history) + [question]
            rows.append((f"r{rid:04d}", t, spec, rng.randint(30, 150)))
            rid += 1
            # The next turn appends the reply *after this same question*, so this
            # turn's whole prompt is a strict prefix of the next turn's. Giving the
            # history entry a different label from the question -- which the first
            # version of this generator did -- silently breaks that prefix relation
            # and makes multi-turn traffic look like independent requests.
            history.append(question)
            history.append(("ANS", f"c{conv:02d}t{turn:02d}", rng.randint(60, 200)))
    build("EXAMPLE_multiturn.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "24 conversations of 3-8 turns. Turn k's prompt is the system prompt plus\n"
          "every earlier question and reply plus the new question, so **turn k's\n"
          "whole prompt is a strict prefix of turn k+1's** -- which is what real\n"
          "multi-turn looks like, and the only shape in which the donor cap in\n"
          "oracle.aligned_ceiling can bind at all.", rows)


def agent():
    rng = LCG(20260819)
    rows = []
    t = 0.0
    rid = 0
    for task in range(20):
        tools = []
        task_prompt = rng.randint(40, 160)
        for step in range(rng.randint(2, 6)):
            t += rng.uniform() * 1.5
            spec = [("SYS", "agent_v2", 420), ("FEW", "tool_schema", 260),
                    ("USR", f"task{task:02d}", task_prompt)]
            spec += list(tools)
            # An agent step answers with a tool call: a handful of tokens.
            rows.append((f"r{rid:04d}", t, spec, rng.randint(2, 24)))
            rid += 1
            # The loop appends the model's own call and the tool's result, so each
            # step's prompt is a strict prefix of the next step's. There is no new
            # user text per step -- the task was stated once, at the front.
            tools.append(("ACT", f"t{task:02d}s{step:02d}", rng.randint(10, 40)))
            tools.append(("TOOL", f"t{task:02d}s{step:02d}", rng.randint(80, 340)))
    build("EXAMPLE_agent.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "20 agent tasks of 2-6 steps. A 420-token system prompt and a 260-token\n"
          "tool schema are shared by everything; the task is stated once and each\n"
          "step appends the model's own tool call and the tool's result, so every\n"
          "step's prompt is a strict prefix of the next step's. Prompts are long,\n"
          "answers are 2-24 tokens, so almost all the compute is prefill and almost\n"
          "all of that prefill is reusable -- which is why this is the shape people\n"
          "quote when selling prefix caching.", rows)


def fewshot():
    rng = LCG(20260820)
    rows = []
    t = 0.0
    tasks = ["math_5shot", "sql_4shot", "code_3shot", "summarise_2shot"]
    lengths = {"math_5shot": 420, "sql_4shot": 380, "code_3shot": 300,
               "summarise_2shot": 150}
    for i in range(140):
        t += rng.uniform() * 2.0
        task = tasks[rng.next() % len(tasks)]
        rows.append((f"r{i:04d}", t,
                     [("SYS", "assistant_v3", 180),
                      ("FEW", task, lengths[task]),
                      ("USR", f"q{i:04d}", rng.randint(20, 80))],
                     rng.randint(40, 200)))
    build("EXAMPLE_fewshot.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "Two levels of sharing: a 180-token system prompt shared by all 140\n"
          "requests, and one of four few-shot blocks shared within a task. The\n"
          "interesting property is that the second level is only reachable through\n"
          "the first -- a prefix cache reuses a prefix, so if the system prompt ever\n"
          "changes, every few-shot block behind it becomes unreachable too.", rows)


def no_sharing():
    rng = LCG(20260821)
    rows = []
    t = 0.0
    for i in range(120):
        t += rng.uniform() * 2.0
        rows.append((f"r{i:04d}", t,
                     [("USR", f"q{i:04d}", rng.randint(200, 900))],
                     rng.randint(40, 200)))
    build("EXAMPLE_no_sharing.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "THE CONTROL. Every request is a single unique segment; nothing is shared\n"
          "with anything. A prefix cache must report a hit rate of exactly zero here.\n"
          "Without this trace the rest of the suite cannot be falsified: a cache that\n"
          "reported hits on everything would look excellent on all six other shapes.", rows)


def shared_last():
    rng = LCG(20260817)     # same seed as system_prompt: same content, moved
    rows = []
    t = 0.0
    for i in range(160):
        t += rng.uniform() * 2.0
        rows.append((f"r{i:04d}", t,
                     [("USR", f"q{i:04d}", rng.randint(24, 90)),
                      ("SYS", "assistant_v3", 180)],
                     rng.randint(40, 240)))
    build("EXAMPLE_shared_last.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "Byte-for-byte the same content as EXAMPLE_system_prompt.csv with the\n"
          "shared 180-token preamble moved *after* the unique question. A prefix\n"
          "cache reuses a prefix, so every one of those tokens becomes unreachable\n"
          "and the hit rate collapses to zero. The fix is a one-line change to prompt\n"
          "assembly, and nothing about the cache configuration can substitute for it.\n"
          "PK001 exists to find this, and this trace exists so the rule can be\n"
          "demonstrated rather than asserted.", rows)


def tiny():
    rows = [
        ("r0000", 0.0, [("SYS", "small", 40), ("USR", "a", 9)], 8),
        ("r0001", 0.5, [("SYS", "small", 40), ("USR", "b", 17)], 8),
        ("r0002", 1.0, [("SYS", "small", 40), ("USR", "c", 33)], 8),
        ("r0003", 1.5, [("SYS", "small", 40), ("FEW", "two", 24), ("USR", "d", 9)], 8),
        ("r0004", 2.0, [("SYS", "small", 40), ("FEW", "two", 24), ("USR", "e", 9)], 8),
        ("r0005", 2.5, [("USR", "f", 64)], 8),
        ("r0006", 3.0, [("SYS", "small", 40), ("USR", "a", 9)], 8),
        ("r0007", 3.5, [("SYS", "other", 33), ("USR", "g", 9)], 8),
        ("r0008", 4.0, [("SYS", "other", 33), ("USR", "h", 9)], 8),
        ("r0009", 4.5, [("SYS", "small", 40), ("FEW", "two", 24), ("USR", "i", 25)], 8),
        ("r0010", 5.0, [("SYS", "small", 40)], 8),
        ("r0011", 5.5, [("SYS", "small", 40), ("USR", "j", 1)], 8),
    ]
    build("EXAMPLE_tiny.csv",
          "SYNTHETIC EXAMPLE -- generated by make_traces.py, not a real capture.\n"
          "Twelve requests, small enough to work out every number with a pencil.\n"
          "Contains the awkward cases on purpose: a request that repeats an earlier\n"
          "one exactly (r0006 = r0000), a request that is a bare shared prefix\n"
          "(r0010), a one-token tail (r0011), a 40-token shared prefix that is not a\n"
          "multiple of 16, and one request sharing nothing (r0005).", rows)


def main():
    system_prompt()
    multiturn()
    agent()
    fewshot()
    no_sharing()
    shared_last()
    tiny()


if __name__ == "__main__":
    main()
